### ISSUE TITLE
Search results in google cal now appear as black on black

### ISSUE THREAD

**Issue by NicolasWebDev** [EvHaus/google-redesigned#37]
Hi,

As stated above, for a few days search results now appear with black font over the black background, making it undistinguishable.

Past events are totally undistinguishable, whereas future events are hard to read.

![Screenshot from 2024-01-09 08-59-33](https://github.com/EvHaus/google-redesigned/assets/2276631/73b1f229-b4c5-471d-804c-e0590bb7c9db)

**Comment by EvHaus** [comment]
Thanks for the report. Should be fixed in the latest version.

**Comment by NicolasWebDev** [comment]
Thanks for the really quick answer @EvHaus !

There was an update in stylus of your style, which I've downloaded, but it seems that only half of the problem was fixed.

![Screenshot from 2024-01-10 08-15-08](https://github.com/EvHaus/google-redesigned/assets/2276631/d05b4323-b73c-45e8-bfb7-f76bc82cfb16)

Future events are still not easily distinguishable.

This is the version I have installed, which corresponds to the last one:
![Screenshot from 2024-01-10 08-17-10](https://github.com/EvHaus/google-redesigned/assets/2276631/a6915a7d-112c-4179-9b20-d88e07d69c86)

**Comment by EvHaus** [comment]
Ah sorry about that. I just pushed a new update. Can you try again?

**Comment by NicolasWebDev** [comment]
Now it's working perfectly @EvHaus , thanks for the responsiveness!
